name: UltimateCore-Alchemy
description: UltimateCore's Alchemy plugin
main: mc.ultimatecore.alchemy.HyperAlchemy
version: 4.0.0
api-version: 1.18
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
commands:
  hyperalchemy:
    description: UltimateCore's Alchemy main command