name: UltimateCore-Alchemy
description: UltimateCore's Alchemy plugin
main: mc.ultimatecore.alchemy.HyperAlchemy
version: 5.2.4
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
commands:
  hyperalchemy:
    description: UltimateCore's Alchemy main command