name: UltimateCore-Dragon
description: UltimateCore's Dragon plugin
main: mc.ultimatecore.dragon.HyperDragons
version: "5.2.7"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ Vault, WorldEdit ]
depend:
    - UltimateCore
commands:
  hyperdragon:
    description: UltimateCore's Dragon main command