name: UltimateCore
description: UltimateCore plugin
main: mc.ultimatecore.helper.UltimatePlugin
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD