name: UltimateCore-Collections
description: UltimateCore's Collections plugin
main: mc.ultimatecore.collections.HyperCollections
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ JetsMinions, UltraMinions, PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core ]
commands:
  collections:
    description: UltimateCore's Collections main command