name: UltimateCore-Reforge
description: UltimateCore's Reforge plugin
main: mc.ultimatecore.reforge.HyperReforge
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Enchantment ]
commands:
  hyperreforge:
    description: Main plugin command