name: UltimateCore-Menu
description: UltimateCore's Menu plugin
main: mc.ultimatecore.menu.HyperCore
version: 4.0.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Crafting, UltimateCore-Skills, UltimateCore-Pets, WorldEdit, WorldGuard, PlaceholderAPI, MVdWPlaceholderAPI, Vault ]
commands:
  hypercore:
    description: UltimateCore's Menu main command