name: UltimateCore
description: UltimateCore's Helper plugin
main: mc.ultimatecore.helper.UltimatePlugin
version: 4.0.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
softdepend: [WorldEdit]
load: POSTWORLD