name: UltimateCore-Pets
description: UltimateCore's Pets plugin
main: mc.ultimatecore.pets.HyperPets
version: 4.0.0
api-version: 1.18
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core, UltimateCore-Skills ]
commands:
  pets:
    description: UltimateCore's Pets main command