name: UltimateCore-Pets
description: UltimateCore's Pets plugin
main: mc.ultimatecore.pets.HyperPets
version: "5.2.7"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core, UltimateCore-Skills ]
depend:
    - UltimateCore
commands:
  pets:
    description: UltimateCore's Pets main command