name: UltimateCore-Collections
description: UltimateCore's Collections plugin
main: mc.ultimatecore.collections.HyperCollections
version: 4.0.0
api-version: 1.18
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, JetsMinions, UltraMinions, PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core ]
commands:
  collections:
    description: UltimateCore's Collections main command