name: UltimateCore-Collections
description: UltimateCore's Collections plugin
main: mc.ultimatecore.collections.HyperCollections
version: "5.2.5"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, JetsMinions, UltraMinions, PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core ]
commands:
  collections:
    description: UltimateCore's Collections main command