name: UltimateCore-Skills
description: UltimateCore-Skills plugin
main: mc.ultimatecore.skills.HyperSkills
version: 4.5.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, JetsMinions, UltraMinions, UltimateCore-Farm, UltimateCore-Anvil, UltimateCore-Crafting, UltimateCore-Enchantment, WorldEdit, WorldGuard, PlaceholderAPI, MVdWPlaceholderAPI, Vault, XMaterial, MythicLib, MythicMobs ]
commands:
  skills:
    description: UltimateCore's Skills main command