name: UltimateCore-Reforge
description: UltimateCore's Reforge plugin
main: mc.ultimatecore.reforge.HyperReforge
version: 5.2.4
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Enchantment ]
commands:
  hyperreforge:
    description: Main plugin command