name: UltimateCore-Reforge
description: UltimateCore's Reforge plugin
main: mc.ultimatecore.reforge.HyperReforge
version: 4.0.0
api-version: 1.18
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Enchantment ]
commands:
  hyperreforge:
    description: Main plugin command