name: UltimateCore-Reforge
description: UltimateCore's Reforge plugin
main: mc.ultimatecore.reforge.HyperReforge
version: "5.2.6"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Enchantment ]
depend:
    - UltimateCore
commands:
  hyperreforge:
    description: Main plugin command