name: UltimateCore-Enchantment
description: UltimateCore's Enchantment plugin
main: mc.ultimatecore.enchantment.EnchantmentsPlugin
version: 5.2.4
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ PlaceholderAPI, MVdWPlaceholderAPI, Vault, AdvancedEnchantments, EcoEnchants ]
commands:
  hyperenchants:
    description: UltimateCore's Enchantment main command