name: UltimateCore-Enchantment
description: UltimateCore's Enchantment plugin
main: mc.ultimatecore.enchantment.EnchantmentsPlugin
version: 4.0.0
api-version: 1.18
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ PlaceholderAPI, MVdWPlaceholderAPI, Vault, AdvancedEnchantments, EcoEnchants ]
commands:
  hyperenchants:
    description: UltimateCore's Enchantment main command