name: UltimateCore-Talismans
description: UltimateCore's Talismans plugin
main: mc.ultimatecore.talismans.HyperTalismans
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, Vault, UltimateCore-Skills ]
commands:
  talismans:
    description: UltimateCore's Talismans main command