name: UltimateCore-Talismans
description: UltimateCore's Talismans plugin
main: mc.ultimatecore.talismans.HyperTalismans
version: 4.0.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, Vault, UltimateCore-Skills ]
commands:
  talismans:
    description: UltimateCore's Talismans main command