name: UltimateCore-Anvil
description: UltimateCore's Anvil plugin
main: mc.ultimatecore.anvil.HyperAnvil
version: 4.0.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ HyperEnchants ]
commands:
  hyperanvil:
    description: UltimateCore's Anvil main command