name: UltimateCore-Crafting
description: UltimateCore's Crafting plugin
main: mc.ultimatecore.crafting.HyperCrafting
version: "5.2.8"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
depend:
    - UltimateCore
load: POSTWORLD
commands:
  hypercrafting:
    description: UltimateCore's Crafting main command