name: UltimateCore-Crafting
description: UltimateCore's Crafting plugin
main: mc.ultimatecore.crafting.HyperCrafting
version: 4.5.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
commands:
  hypercrafting:
    description: UltimateCore's Crafting main command