name: UltimateCore-Runes
description: UltimateCore's Runes plugin
main: mc.ultimatecore.runes.HyperRunes
version: "5.2.6"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore-Skills ]
depend:
    - UltimateCore
commands:
  hyperrunes:
    description: UltimateCore's Runes main command