name: UltimateCore-Trades
description: UltimateCore's Trades plugin
main: mc.ultimatecore.trades.HyperTrades
version: "5.2.5"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
depend: [ Vault ]
commands:
  hypertrades:
    description: UltimateCore's trades main command