name: UltimateCore-Trades
description: UltimateCore's Trades plugin
main: mc.ultimatecore.trades.HyperTrades
version: "5.2.7"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
depend: [ Vault ]
depend:
    - UltimateCore
commands:
  hypertrades:
    description: UltimateCore's trades main command