name: UltimateCore-Trades
description: UltimateCore's Trades plugin
main: mc.ultimatecore.trades.HyperTrades
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
depend: [ Vault ]
commands:
  hypertrades:
    description: UltimateCore's trades main command