name: UltimateCore-Souls
description: UltimateCore's Souls plugin
main: mc.ultimatecore.souls.HyperSouls
version: "5.2.5"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core ]
commands:
  souls:
    description: UltimateCore's Souls main command