name: UltimateCore-Souls
description: UltimateCore's Souls plugin
main: mc.ultimatecore.souls.HyperSouls
version: "5.2.8"
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core ]
depend:
    - UltimateCore
commands:
  souls:
    description: UltimateCore's Souls main command