name: UltimateCore-Farm
description: UltimateCore's Farm plugin
main: mc.ultimatecore.farm.HyperRegions
version: ${version}
api-version: ${minecraft.api.version}
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, WorldEdit, WorldGuard, Multiverse-Core, Residence, UltraRegions ]
commands:
  ultimatefarm:
    aliases: [ "ucfarm" ]
    description: UltimateCore's Farm main command