name: UltimateCore-Farm
description: UltimateCore's Farm plugin
main: mc.ultimatecore.farm.HyperRegions
version: 4.5.0
api-version: 1.13
authors: [ EduardWayland, ZubeySweet ]
load: POSTWORLD
softdepend: [ UltimateCore, WorldEdit, WorldGuard, Multiverse-Core, Residence, UltraRegions ]
commands:
  ultimatefarm:
    aliases: [ "ucfarm" ]
    description: UltimateCore's Farm main command